### ISSUE TITLE
Tutorial 5 provided classes

### ISSUE THREAD

**Issue by Jittybug** [ZeyadAlshaikh/CS141-1-23-Tutorials#1]
السلام عليكم ورحمة الله وبركاته
يادكتور الكلاسات الي تجي مع تتوريال 5 ميب موجوده بالقيتهوب فياليت تنزلها
شكرا :)

**Comment by ZeyadAlshaikh** [comment]
عليكم السلام ورحمة الله وبركاته جميع الملفات موجودة على الرابط التالي ZeyadAlshaikh - Overviewgithub.comSent from my iPhoneOn 16 Oct 2023, at 7:05 AM, Jittybug ***@***.***> wrote:﻿
السلام عليكم ورحمة الله وبركاته
يادكتور الكلاسات الي تجي مع تتوريال 5 ميب موجوده بالقيتهوب فياليت تنزلها
شكرا :)
